### ISSUE TITLE
Can stdout and stderr be the same file?

### ISSUE THREAD

**Issue by kbenzie** [sheredom/process.h#2]
Is it possible to make stdout and stderr be the same `FILE*`? This can be
useful when for getting the full context of a processes failure, or if the
intention is to show its output in order as if in a terminal.

**Comment by sheredom** [comment]
I don't know for sure if its possible but I'll certainly look at adding it!

**Comment by sheredom** [comment]
Fixed in https://github.com/sheredom/process.h/pull/3 - please take a look!
