### ISSUE TITLE
Lib just dont work

### ISSUE THREAD

**Issue by TheCherry** [sheredom/process.h#9]
Hallo,
I was very happy to find this lib.
But it just doesn't work.

I tried it with C and C++ in MVS 2017.
At the example
```c
	const char *command_line[] = { "echo", "\"Hello, world!\"", NULL };
	struct process_s process;
	int result = process_create(command_line, 0, &process);
	if (0 != result) {
		// an error occurred!
	}
```
I always get the result -1
If I start nodejs instead of echo, a result of 0 comes but the process does not start.

**Comment by sheredom** [comment]
Is `echo` on the path? How do you know that `nodes` does not start?

**Comment by sheredom** [comment]
Closing this as no-response to my queries.
